---

- docker_service:
    project_name: web
    definition:
      version: "2.3"
      services:
        web:
          image: "gargron/mastodon:v{{ mastodon_release }}"
          networks:
            - "{{ mastodon_docker_network }}"
          command: bundle exec rails s -p 3000 -b '0.0.0.0'
          restart: on-failure
          env_file: /mastodon/.env
      networks:
        "{{ mastodon_docker_network }}":
          external: true
  notify: "restart caddy webserver"
